version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: get-file-data:latest
    working_dir: /app
    restart: unless-stopped
    environment:
      - 'NODE_ENV=development'
    command: ['npm', 'start']
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    ports:
      - 8000:${SERVER_PORT}
